decsription_token = """
For accessing the protected API resources, you must have received a a valid JWT token after registering or logging in. This JWT token must then be used for all protected resources by passing it in via the 'Authorization' header.

A JWT token is generated by the API by either registering via /users or logging in via /users/login.

The following format must be in the 'Authorization' header :

Token xxxxxx.yyyyyyy.zzzzzz
"""
